service: baladi

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x

functions:
  api:
    handler: apps/api/index.handler
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}
